version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db-dockerfile
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: trire123
      POSTGRES_DB: weg
#volumes persists db across container instances
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  weg-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      - "db"
    links:
      - db
