version: '3'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: trire123
      POSTGRES_DB: weg
    ports: 
      - "5432:5432"
  weg-api:
    image: weg-api
    container_name: weg-api
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      - "db"
